### ISSUE TITLE
How to use.

### ISSUE THREAD

**Issue by Chris2011** [rishabh-ink/peek-into-github#3]
Hi,

how can I use it?. No tutorial for this? I only see an entry "Pig" inside window tab and then a new little window opens as your screenshot shows. Only click on refresh, after click on refresh I got a NullPointerException. After click on refresh twice I got this: Peek into github. Oops I bumped into an error. But I can't see an error, only inside the IDE log: http://pastebin.com/Nvp6QsM9
No login prompt comes up. I use Netbeans 8.0 for Windows 7 64bit.
Hope the report helps you.

Cheers

Chris

**Comment by Chris2011** [comment]
The plugin was removed from the Netbeans plugin page? oO What happens. And what about the error with the exception, when I try to connect with github via netbeans?

**Comment by rishabh-ink** [comment]
Sorry, this project is no longer maintained. NetBeans now has in-built support for Git and GitHub. Thus, this plugin was deprecated and removed.

**Comment by Chris2011** [comment]
There is no build in support for github, what your plugin did. Your plugin brings a functionality to netbeans which is not in. But I work on another plugin: https://github.com/Chris2011/Github-Repository-Viewer
